### PR TITLE
Readable README

### PR DESCRIPTION
**Pull request by EQt**
Point out to the docs/ directory and the LICENSE file

### CODE REVIEW

**Comment by EQt** [comment]
Make script work out of the box

**Comment by EQt** [comment]
Python3 support

**Comment by kjellmf** [comment]
Thanks for the pull request @EQt! I'm currently on a vacation and away from my computer. I'll review the PR when I return.

**Comment by kjellmf** [comment]
Have you checked that you changes are compatible with Python 2.7? I failed to run the tests in `test_svg2tikz.py` using Python 2.7 due to an import error. The clipboard functionality also fails on windows because you have replaced `unicode(text, 'utf8')` with `str(text, 'utf8')`.

**Comment by kjellmf** [comment]
It looks like the `open_anything` function is the problem, or actually two problems. The use of `urllib.request` and `io` instead of `StringIO`.

**Comment by EQt** [comment]
Oh, you are right: I did not run the tests. I will fix that, maybe by reverting some of the python3 stuff.

**Comment by EQt** [comment]
Now the tests/test_*.py scripts fail for the same reasons as on your master branch in python2.7

**Comment by kjellmf** [comment]
Thanks for the contribution @EQt ! I modified the PR slightly so that the clipboard works in 2.7.

**Pull request merged**
